version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "swordfish"
      POSTGRES_DB: "timekeeper"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
